print ("Hello, World!")
print("Muhammad Talal")
print("Muhammad Talal Mustafa Khan")
print(1,2,3)
print("Hello\nWorld")
print("Hello\tWorld")
print('apple', 'banana', 'cherry', sep=', ')
print(1, 2, 3, sep='-')
print('Hello', end=' ')
print('World')
print(1, end='')
print(2)
print('He said, "Hello!"')
print('This is a backslash: \\')
age = 20
print('I am', age, 'years old')
n = 5
print('The number is', n)
for i in range(1, 6):
    print(i)
